/**
 * Shared brand / cognate allowlist used by i18n page scanners across all packages.
 * Words in this set are allowed to appear as 4+ char ASCII-Latin runs in non-English locales.
 */
export const BRAND_ALLOW_LIST = new Set([
  // ── Brand names ──────────────────────────────────────────────────────
  'WhyNot QA',
  'WhyNot',
  'QA Loop',
  'MCP',
  'Stripe',
  'GitHub',
  'Google',
  'CI/CD',
  'Slack',
  'Webhook',
  'Webhooks',
  'Playwright',
  'Gemini',
  'BrowserStack',
  'LambdaTest',
  'Cypress',
  'Selenium',
  'OpenAI',
  'Anthropic',
  'OpenRouter',
  'X (Twitter)',

  // ── Technical acronyms / abbreviations ───────────────────────────────
  'CSV',
  'JSON',
  'UUID',
  'URL',
  'JWT',
  'MRR',
  'ARR',
  'API',
  'DOM',
  'DAU',
  'MAU',
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
  'p95',
  'p99',
  'req/s',

  // ── Example / placeholder strings ────────────────────────────────────
  'you@example.com',
  'admin@example.com',
  '••••••••',
  'https://example.com',
  'https://example.com/webhook',
  'https://example.com (optional)',
  'sk-...',
  'optional',

  // ── International cognates — same word in many languages ─────────────
  'Actual',
  'Action',
  'Actions',
  'Admin',
  'Actor',
  'Assertions',
  'Audit',
  'Blog',
  'Branch',
  'Browser',
  'Budget',
  'Bugs',
  'Color',
  'Community',
  'Configuration',
  'Console',
  'Contact',
  'Credits',
  'Dashboard',
  'Date',
  'Description',
  'Descriptions',
  'Details',
  'Documentation',
  'Downgrade',
  'Element',
  'Endpoint',
  'Enterprise',
  'Error',
  'Flag',
  'Flags',
  'General',
  'Headless',
  'Info',
  'Iteration',
  'Iter',
  'Legal',
  'Menu',
  'Name',
  'Navigation',
  'Notifications',
  'Page',
  'Pages',
  'Pause',
  'Performance',
  'Permissions',
  'Plan',
  'Plans',
  'Public',
  'Repository',
  'Rollout',
  'Screenshot',
  'Screenshots',
  'Selector',
  'Slug',
  'Status',
  'Super Admin',
  'Support',
  'System',
  'Tests',
  'Trace',
  'Type',
  'Upgrade',
  'User Story',
  'Version',
  'Website',

  // ── German/English shared loan words (4+ ASCII chars) ────────────────
  'CTO',
  'Test',
  'Code',
  'Mode',
  'Note',
  'Link',
  'Team',
  'Chat',
  'Profile',
  'Online',
  'Sprint',
  'Limit',
  'Token',
  'Provider',
  'Scanner',
  'Monitor',
  'Monitors',
  'Filter',
  'Export',
  'Import',
  'Inline',
  'Login',
  'Logout',
  'Webhook',
  'Timeout',
  'Setup',

  // ── Additional cognates found across locale files ─────────────────────
  'Stories',
  'Suites',
  'Experimental',
  'PR',
  '{{formattedCount}} req',
  '90% (strict)',
  'Element:',
  '{{count}} endpoints',
  'Excellent',

  // ── French/English shared cognates (4+ ASCII chars) ──────────────────
  'Service',
  'Suite',
  'Route',
  'Simple',
  'Table',
  'Principal',
  'Visible',

  // ── Spanish/English shared cognates (4+ ASCII chars) ─────────────────
  'Total',
  'Normal',
  'Local',

  // ── Interpolation templates ──────────────────────────────────────────
  'Bugs ({{count}})',
  'Pages ({{count}})',
  'Tests ({{count}})',
  'Screenshots ({{count}})',
  'Screenshot {{index}}',
  'Version {{version}}',
  'WhyNot QA v{{version}}',
  '{{count}} bugs',
  '{{count}} pages',
  '{{count}} tests',
  '{{count}} user stories',
  '{{from}} — {{to}}',
  '{{price}}/{{interval}}',

  // ── Testimonial proper names ─────────────────────────────────────────
  'Sarah Chen',
  'ShopFlow',
  'Marcus Johnson',
  'LaunchPad AI',
  'Elena Rodriguez',
  'Meridian Health',

  // ── Short identifiers allowed as single tokens ───────────────────────
  'ID',
  'No',
  'ms',
  'or',
]);
