from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from enum import Enum


class ActionType(str, Enum):
    NAVIGATE = "navigate"
    CLICK = "click"
    TYPE = "type"
    FILL = "fill"
    SELECT = "select"
    WAIT = "wait"
    ASSERT = "assert"
    SCROLL = "scroll"
    HOVER = "hover"


class ElementDescription(BaseModel):
    """Description of an element to interact with"""
    text: Optional[str] = None
    role: Optional[str] = None
    label: Optional[str] = None
    placeholder: Optional[str] = None
    position: Optional[str] = None  # e.g., "first button", "last input"
    attributes: Optional[Dict[str, str]] = None


class ElementSelector(BaseModel):
    """Selector for locating an element"""
    type: str  # 'data-testid' | 'id' | 'class' | 'text' | 'xpath' | 'css' | 'aria-label' | 'visual'
    value: str
    stability_score: float
    confidence: Optional[float] = None


class TestStep(BaseModel):
    """A single atomic test step"""
    id: str
    action: ActionType
    target: Optional[ElementDescription] = None
    value: Optional[str] = None  # For type/fill actions
    expected_outcome: Optional[str] = None
    wait_time: Optional[int] = None  # milliseconds
    description: str
    suggested_selectors: Optional[List[ElementSelector]] = None  # Selectors generated by Claude
    
    class Config:
        """Pydantic configuration to include None values in serialization"""
        exclude_none = False


class TestCase(BaseModel):
    """A complete test case with multiple steps"""
    id: str
    name: str
    description: str
    steps: List[TestStep]
    website_url: str
    metadata: Optional[Dict[str, Any]] = None


class UserStory(BaseModel):
    """User story input"""
    story: str
    website_url: str
    additional_context: Optional[str] = None


class VisionAnalysisResult(BaseModel):
    """Result from vision AI analysis"""
    elements: List[Dict[str, Any]]
    text_elements: List[Dict[str, Any]]
    layout_info: Optional[Dict[str, Any]] = None

