-- Migration: 013_tiered_models.sql
-- Phase 6: Tiered AI Model Strategy
-- Track which Claude model is used per iteration for cost optimization

-- Add model tracking to iterations table
ALTER TABLE qa_loop_iterations ADD COLUMN IF NOT EXISTS model_used VARCHAR(50);
ALTER TABLE qa_loop_iterations ADD COLUMN IF NOT EXISTS input_tokens INTEGER DEFAULT 0;
ALTER TABLE qa_loop_iterations ADD COLUMN IF NOT EXISTS output_tokens INTEGER DEFAULT 0;
ALTER TABLE qa_loop_iterations ADD COLUMN IF NOT EXISTS cost_cents DECIMAL(10,4) DEFAULT 0;

-- Add tokens by model tracking to budget table
ALTER TABLE qa_loop_budget_tracking ADD COLUMN IF NOT EXISTS tokens_by_model JSONB DEFAULT '{}';

-- Add model usage summary to sessions
ALTER TABLE qa_loop_sessions ADD COLUMN IF NOT EXISTS model_usage_summary JSONB DEFAULT '{}';

-- Create index for model-based analytics
CREATE INDEX IF NOT EXISTS idx_qa_loop_iterations_model ON qa_loop_iterations(model_used);

-- Create view for model usage analytics
CREATE OR REPLACE VIEW qa_loop_model_analytics AS
SELECT 
    session_id,
    model_used,
    COUNT(*) as iteration_count,
    SUM(input_tokens) as total_input_tokens,
    SUM(output_tokens) as total_output_tokens,
    SUM(cost_cents) as total_cost_cents,
    AVG(cost_cents) as avg_cost_per_iteration
FROM qa_loop_iterations
WHERE model_used IS NOT NULL
GROUP BY session_id, model_used;

-- Add comment for documentation
COMMENT ON COLUMN qa_loop_iterations.model_used IS 'Claude model used: claude-3-haiku-20240307, claude-sonnet-4-20250514, or claude-3-opus-20240229';
COMMENT ON COLUMN qa_loop_iterations.input_tokens IS 'Number of input tokens consumed by this iteration';
COMMENT ON COLUMN qa_loop_iterations.output_tokens IS 'Number of output tokens generated by this iteration';
COMMENT ON COLUMN qa_loop_iterations.cost_cents IS 'Estimated cost in cents for this iteration';
